### ISSUE TITLE
Solegnolia doesnt disrupt ring of magnetization

### ISSUE THREAD

**Issue by Makin91** [williewillus/Botania#118] opened 2016-02-16 19:57 UTC
on version Beta 0.5.4.1

**Comment by williewillus** [comment] 2016-02-16 20:17
put on the manaseer monocles and make sure the item is actually within range of the flower.
show screenshots of your setup, also.

**Comment by williewillus** [comment] 2016-02-18 15:08
I can't reproduce

**Comment by yrsegal** [comment] 2016-02-19 02:47
he probably powered it

**Comment by williewillus** [comment] 2016-02-19 14:32
yeah closing for now

**Closed as completed by williewillus** 2016-02-19 14:32 UTC
Labels: mechanic, cant-reproduce, need-response
