### ISSUE TITLE
[ALL] The master "receiveMana crash" thread

### ISSUE THREAD

**Issue by Carrots4U** [williewillus/Botania#71] opened 2016-01-24 04:09 UTC
I am on the latest build of Botania, which I downloaded instantly because I was hoping it would fix any other botania crashes I was getting totally randomly. I was walking around and poof, once again, crashed. 

Crashlog: 

http://pastebin.com/bfLYhNMS

**Comment by Carrots4U** [comment] 2016-01-24 04:24
Another, different, crash experienced just walking around, http://pastebin.com/GqKvbTdb

**Comment by dragsta** [comment] 2016-01-24 04:43
This is the same issue I was having and reported from the previous non 5.2 build

**Comment by williewillus** [comment] 2016-01-24 05:04
I'm at a loss here, I haven't even identified the main issue and even the band aids aren't working. I'm so sorry >.<

Can I get some info about these? Namely
- I've noticed all the reports have been on MP servers. What is the view distance of the server set on, and what is the view distance of your client?
- Can you reliably reproduce the crash every time by crossing some chunk boundary?

**Comment by Carrots4U** [comment] 2016-01-24 05:09
My client's view distance is set to 7, and server's is set to 10. The crash seems to only occur when our Botania tree farm is activated, and the crash itself is random very time. Sometime it happens instantly on logging in, others it can take 10 minutes. No need to apologize though! It must be hard porting such a huge mod as Botania to 1.8.9 without coming across some issue.

**Comment by williewillus** [comment] 2016-01-24 05:10
If at all convenient, can I see a screenshot of the farm? (Wherever the functional flower that crashes is located and how it's being fed)

**Comment by Carrots4U** [comment] 2016-01-24 05:11
You can join the server yourself to experience firsthand if you'd like. I'm on the same server as another bug reporter, whatthedrunk.

http://i.imgur.com/5sOTn1k.jpg

**Comment by williewillus** [comment] 2016-01-24 05:14
Sure, is there a pack I need to have?

**Comment by Carrots4U** [comment] 2016-01-24 05:15
Do you have a reddit account? We have a private subreddit with the IP and pack download listed. Edit: seems like whatthedrunk just added you to subreddit, it should be in the top sticky post.

**Comment by williewillus** [comment] 2016-01-24 05:16
yes, /u/williewillus

**Comment by whatthedrunk** [comment] 2016-01-24 05:17
I added you to the sub, the sticky here has all the info https://www.reddit.com/r/allthemods/comments/42eese/drunken_fumble_v17_is_out/

**Comment by williewillus** [comment] 2016-01-24 05:17
thank you!

**Comment by whatthedrunk** [comment] 2016-01-24 05:28
I sent you a PM with the correct config files. The sticky there forgot to add them to the download. We were in a rush to get your new build up.

**Comment by williewillus** [comment] 2016-01-24 06:03
@whatthedrunk new build in releases

**Comment by whatthedrunk** [comment] 2016-01-24 06:27
playing with the update but I just got a new crash with it. http://pastebin.com/ANu0Q53K

**Comment by whatthedrunk** [comment] 2016-01-24 06:28
The new update is exactly the same with the new botania if you would like to login and look.

**Comment by Carrots4U** [comment] 2016-01-24 06:34
Seems like the new crash is because of the hopperhock?  
 vazkii.botania.common.block.subtile.functional.SubTileHopperhock.renderHUD(SubTileHopperhock.java:243)

**Comment by whatthedrunk** [comment] 2016-01-24 06:52
seems to be working fine now with a floating hopper fyi. Thanks a ton!

**Comment by MaPePeR** [comment] 2016-01-24 12:04
@williewillus have you figured out if its `worldObj` or `worldObj.getBlockState(pos)` that causes the NPE in [this line](https://github.com/williewillus/Botania/blob/MC18/src/main/java/vazkii/botania/common/block/tile/mana/TilePool.java#L123)?

**Comment by williewillus** [comment] 2016-03-02 16:31
I think we found the cause of this one, and it was a lot more trivial than I thought >.>
Next build should hopefully see a real fix for this instead of the bandaid we have now

**Closed as completed** 2016-03-02 16:31 UTC
Labels: help wanted, mechanic
