### ISSUE TITLE
TC5/Botania -> Botanurgists Inkwell does not work in research table ("out of ink")

### ISSUE THREAD

**Issue by Ioandar** [williewillus/Botania#91] opened 2016-01-31 11:15 UTC
works fine in Inventory (creating new research note with thaumanomicon)

does **not** work in research table. table reports "out of ink"

Forge1726, TC5.1.4, Botania.r1.8-248-MC1.8-779cc76

**Comment by GirafiStudios** [comment] 2016-01-31 17:40
It works just fine, you just have to fill some mana in it first.

**Comment by williewillus** [comment] 2016-01-31 18:17
@GirafiStudios is that how it used to work in 1.7? Getting a lot of reports that it doesn't work but idk if it's just works as intended :p

**Comment by yrsegal** [comment] 2016-01-31 18:18
it is how it worked in 1.7.

**Comment by Ioandar** [comment] 2016-01-31 21:47
just tried again and you are right, it works

I guess I was daydreaming then and did oversee that I still had a filled normal scribing tool in my inventory (so thauminomicon worked) and did not realize that the Botanurgists Inkwell was indeed empty when I put it into the table... herbyderp me then :)

okay, that is how it works them:
I throw a fully filled Inkwell into the mana pool and get an empty Botanurgists Inkwell (that looks like it is full) back that I have to throw again into a mana pool to actually fill it...

In the following picture I have 1 filled and 1 empty in my inventory. which is which? :)

http://postimg.org/image/medhmfwe7/

maybe it will help derpies like me to have a more visual 'I am empty' Botanurgists Inkwell?

another idea would be to fill it when you have a mana tablet in your inventory...

**Comment by howtonotwin** [comment] 2016-01-31 23:47
There's a method (`Item.showDurabilityBar()`) that is called to determine if the durability bar should be shown. Perhaps override it and show an empty bar when the inkwell is empty instead of letting it disappear?

**Comment by howtonotwin** [comment] 2016-02-01 00:49
This is actually also present in 1.7. Perhaps you should create a new issue there?

EDIT: Pull request coming Soon™.

**Comment by TheWhiteWolves** [comment] 2016-02-01 09:39
@williewillus you can probably close this one now

**Comment by howtonotwin** [comment] 2016-02-01 11:31
This will close as soon as he pulls in upstream, and IMO that looks a lot neater.

**Comment by Ioandar** [comment] 2016-02-01 12:43
tyvm, you are awesome!

**Closed as completed** 2016-02-01 12:46 UTC
