### ISSUE TITLE
[1.10.2] Mana Flowers model doesn't work on world re-load, requires re-placing them

### ISSUE THREAD

**Issue by oitsjustjose** [williewillus/Botania#419] opened 2016-08-01 23:36 UTC
Forge Version: 12.18.1.2044
Botania Version: r1.8-314
[Full Mod-List](http://puu.sh/qmxP6/aaf345e284.png)

So, this is an interesting bug. When ever I re-load / re-log a world / server, all of my magical flowers lose their model. They revert to the cuboid model (yet retaining their flower block off-set) and the Magenta & Black texture. This also occurs whenever the client unloads and reloads the chunks from rendering (the area is chunkloaded and on a server in my victim-case).

Here are some photos further showing the issue:

![2016-08-01_18 26 56](https://cloud.githubusercontent.com/assets/3887324/17312199/a6b2b1e4-5816-11e6-8fcc-bc2249073115.png)

In the next image, you can see WAILA knows their model and texture just fine, but the game renderer has no clue:

![2016-08-01_18 30 07](https://cloud.githubusercontent.com/assets/3887324/17312206/b7aadd78-5816-11e6-91ab-7462dae9811c.png)

Lastly: here's with my Pure Daisies being broken and re-placed. It does not update nearby pure daisies, or other flowers, just the ones you break and re-place:

![2016-08-01_18 30 16](https://cloud.githubusercontent.com/assets/3887324/17312224/ca585310-5816-11e6-87b4-02ab190b1be9.png)

**Comment by yrsegal** [comment] 2016-08-01 23:37
Dupe of #416

**Comment by oitsjustjose** [comment] 2016-08-01 23:43
..but but I am on Forge 2044! 

That's what was claimed as the solution! :P

EDIT: 

> Figured it out. Next build (in a couple days) will have a fix

Didn't see that. Sorry ._.

**Comment by WtfShipoopi** [comment] 2016-08-02 02:09
Makes me not even wanna play... Sometime the plants are just completely gone for me..

**Comment by yrsegal** [comment] 2016-08-02 02:09
well, be patient :P

**Comment by WtfShipoopi** [comment] 2016-08-02 02:11
Lol, I am we just stopped our server and took a back up waiting for a fix till then We will go back to our AG2 server..

**Comment by williewillus** [comment] 2016-08-02 02:20
new release tomorrow, hang in there

**Closed as completed by williewillus** 2016-08-02 02:20 UTC

**Comment by psychofad** [comment] 2016-08-03 21:55
I guess Tomorrow really meant Soon™ :P

**Comment by oitsjustjose** [comment] 2016-08-03 21:56
I mean, modders have other lives and priorities - rushing people (and even briefly, positively mentioning elapsed time is rushing) by no means helps.

Take your time guys - the mod works just fine without the fix, it's just an added challenge having to guess which flower is which ;)

**Comment by williewillus** [comment] 2016-08-03 21:59
Yeah sorry, family thing Monday then totally forgo yesterday. Will do for sure this evening

**Comment by oitsjustjose** [comment] 2016-08-03 22:00
Just whenever, real life before the modding life!

**Comment by WtfShipoopi** [comment] 2016-08-03 22:26
Completely agree with the above.. :D
