### ISSUE TITLE
 doesn't work (with thaumcraft perhaps)

### ISSUE THREAD

**Issue by jawsawn** [williewillus/Botania#58] opened 2016-01-20 22:34 UTC
https://gyazo.com/63b23d5326d1356cb2460c40d4f34be1

I had this screen. The issue solved when I removed botania. I can supply more info if needed. 

I was going to post this for 0.5 beta but I realized using 0.4.1 alpha gave me the same error. 

Using TC 5.1.4, Baubles-1.8.9-1.1.3.0 forge version forge-1.8.9-11.15.0.1710

**Comment by yrsegal** [comment] 2016-01-20 22:35
duplicate of #53

**Closed as completed** 2016-01-21 00:01 UTC
