### ISSUE TITLE
Saplings

### ISSUE THREAD

**Issue by Majestyc2k1** [williewillus/Botania#85] opened 2016-01-28 19:23 UTC
Saplings are disappearing when used in the Alchemy Catalyst.

**Comment by williewillus** [comment] 2016-01-28 19:27
What do you mean? like they just get eaten and nothing comes back?

**Comment by GirafiStudios** [comment] 2016-01-28 19:30
What kind of saplings? I just tested oak saplings and you get spruce saplings, no problem there :)
And what build of Botania are you using?

**Comment by yrsegal** [comment] 2016-01-28 22:16
are there any endoflames nearby?

**Comment by Majestyc2k1** [comment] 2016-01-28 22:33
Yes, there are endoflames nearby. I put in a birch to make a jungle, but it disappeared/got eaten. Nothing returned. I also tried oak, same thing. I tried it on both 0.5.2.2 and 0.5.3.

**Comment by yrsegal** [comment] 2016-01-28 22:34
Yeah. Endoflames do that. This has been closed as intended on upstream many, many times.

**Comment by yrsegal** [comment] 2016-01-28 22:34
If you want, give it a whirl with endoflames in the same places in 1.7. Same thing happens. Seperate mana production and mana usage.

**Closed as completed** 2016-01-29 06:24 UTC

**Comment by Majestyc2k1** [comment] 2016-01-29 07:15
So nothing is going to be done to fix this?

**Comment by GirafiStudios** [comment] 2016-01-29 08:32
It's a problem with how you have setup your stuff..

**Comment by howtonotwin** [comment] 2016-01-29 22:26
Why do you not expect an Endoflame to burn a piece of fuel when it's in range? This is 100% intended behavior.

**Comment by Majestyc2k1** [comment] 2016-01-30 19:12
If I throw something into the Catalyst (especially when the screen shows the transformation) and the visual and audio effect plays like any other item, I expect it to work. But anyways, I will make a different setup. Thank you for the information.
