### ISSUE TITLE
Crash when hovering over Fallen Kanade before placing mana pool

### ISSUE THREAD

**Issue by OuweMickey** [williewillus/Botania#84] opened 2016-01-27 16:09 UTC
http://pastebin.com/cGeELSvZ

I have a crash I can't get out anymore (when loading savegame it instantly crashes)
I've checked when it happens (tried multiple test worlds):
1. place Fallen Kanade (or floating)
2. place Mana Pool
3. Hover over Fallen Kanade (with wand of the forest)
4. Crash (and can't reload savegame anymore)

It won't happen when first placing mana pool
I guess I have to wait for an update for a fix before I can load up my world (or I'll have to get my 10 hours ago backup :P)

Tnx!

**Comment by williewillus** [comment] 2016-01-27 16:27
Duplicate of #73, fixed in latest build

**Closed as completed by williewillus** 2016-01-27 16:27 UTC

**Comment by Hyxaru** [comment] 2016-01-28 08:37
While the game loads you can spam any key in for your hotbar that does not contain the wand, so if it is in your seventh hotbar slot you can spam key 1 for example.
