### ISSUE TITLE
Crash after removing BoP

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#147] opened 2016-02-29 15:26 UTC
After I removed BoP for certain reasons, looking up in the creative search tab and botania tab crashes the game. 
Looks like BoP added a status effect Botania had an incense stick for, and now BoP is gone it has an invalid incense.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 29-2-16 16:23
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
    at vazkii.botania.common.item.brew.ItemIncenseStick.getItemForBrew(ItemIncenseStick.java:110)
    at vazkii.botania.common.item.brew.ItemIncenseStick.func_150895_a(ItemIncenseStick.java:48)
    at vazkii.botania.common.core.BotaniaCreativeTab.addItem(BotaniaCreativeTab.java:417)
    at vazkii.botania.common.core.BotaniaCreativeTab.func_78018_a(BotaniaCreativeTab.java:142)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:450)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:427)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:564)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:534)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at vazkii.botania.common.item.brew.ItemIncenseStick.getItemForBrew(ItemIncenseStick.java:110)
    at vazkii.botania.common.item.brew.ItemIncenseStick.func_150895_a(ItemIncenseStick.java:48)
    at vazkii.botania.common.core.BotaniaCreativeTab.addItem(BotaniaCreativeTab.java:417)
    at vazkii.botania.common.core.BotaniaCreativeTab.func_78018_a(BotaniaCreativeTab.java:142)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:450)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:427)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:564)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:534)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Hyxaru'/411, l='MpServer', x=-824,74, y=66,38, z=244,76]]
    Chunk stats: MultiplayerChunkCache: 289, 289
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: -922,00,4,00,192,00 - World: (-922,4,192), Chunk: (at 6,0,0 in -58,12; contains blocks -928,0,192 to -913,255,207), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
    Level time: 1106270 game time, 6000 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 42 total; [EntityItem['item.tile.livingrock0'/258, l='MpServer', x=-823,56, y=63,88, z=247,46], EntityThaumcraftGolem['Golem'/259, l='MpServer', x=-823,41, y=63,88, z=247,97], EntityThaumcraftGolem['Golem'/260, l='MpServer', x=-820,25, y=63,88, z=245,53], EntityItem['item.tile.livingrock0'/261, l='MpServer', x=-821,88, y=63,88, z=249,41], EntityItem['item.tile.livingrock0'/262, l='MpServer', x=-823,88, y=63,88, z=249,88], EntityItem['item.tile.livingrock0'/263, l='MpServer', x=-820,47, y=63,88, z=247,78], EntityItem['item.tile.livingrock0'/264, l='MpServer', x=-821,13, y=63,88, z=248,91], EntityItem['item.tile.livingrock0'/265, l='MpServer', x=-824,00, y=66,00, z=246,91], EntityItem['item.tile.livingrock0'/266, l='MpServer', x=-822,88, y=65,00, z=248,16], EntityAuraNode['Aura Node'/267, l='MpServer', x=-798,50, y=85,50, z=361,50], EntityAuraNode['Aura Node'/274, l='MpServer', x=-781,50, y=64,50, z=213,50], EntityAuraNode['Aura Node'/275, l='MpServer', x=-770,50, y=65,50, z=270,50], EntityAuraNode['Aura Node'/277, l='MpServer', x=-757,50, y=74,50, z=298,50], EntityItemFrame['entity.ItemFrame.name'/164, l='MpServer', x=-837,50, y=65,50, z=120,03], EntityItemFrame['entity.ItemFrame.name'/171, l='MpServer', x=-839,50, y=65,50, z=120,03], EntityItemFrame['entity.ItemFrame.name'/172, l='MpServer', x=-841,50, y=65,50, z=120,03], EntityItemFrame['entity.ItemFrame.name'/173, l='MpServer', x=-843,50, y=65,50, z=120,03], EntityAuraNode['Aura Node'/430, l='MpServer', x=-708,50, y=65,50, z=196,50], EntityItemFrame['entity.ItemFrame.name'/174, l='MpServer', x=-845,50, y=65,50, z=120,03], EntityItemFrame['entity.ItemFrame.name'/175, l='MpServer', x=-847,50, y=65,50, z=120,03], EntityPlayerSP['Hyxaru'/411, l='MpServer', x=-824,74, y=66,38, z=244,76], EntityAuraNode['Aura Node'/54, l='MpServer', x=-908,50, y=75,50, z=357,50], EntityCorporeaSpark['Corporea Spark'/186, l='MpServer', x=-845,50, y=63,50, z=184,50], EntityCorporeaSpark['Corporea Spark'/187, l='MpServer', x=-846,50, y=63,50, z=185,50], EntityThaumcraftGolem['Golem'/188, l='MpServer', x=-847,50, y=63,00, z=196,41], EntityThaumcraftGolem['Golem'/189, l='MpServer', x=-846,53, y=63,00, z=192,94], EntityItemFrame['entity.ItemFrame.name'/61, l='MpServer', x=-865,97, y=68,50, z=135,50], EntityItemFrame['entity.ItemFrame.name'/62, l='MpServer', x=-867,50, y=68,50, z=134,97], EntityItemFrame['entity.ItemFrame.name'/63, l='MpServer', x=-867,97, y=68,50, z=134,50], EntityItemFrame['entity.ItemFrame.name'/64, l='MpServer', x=-867,97, y=68,50, z=136,50], EntityItemFrame['entity.ItemFrame.name'/65, l='MpServer', x=-870,50, y=68,50, z=134,97], EntityItemFrame['entity.ItemFrame.name'/66, l='MpServer', x=-869,50, y=68,50, z=134,97], EntityThaumcraftGolem['Golem'/195, l='MpServer', x=-842,00, y=63,00, z=187,38], EntityAuraNode['Aura Node'/75, l='MpServer', x=-868,50, y=77,50, z=334,50], EntityItemFrame['entity.ItemFrame.name'/78, l='MpServer', x=-849,50, y=65,50, z=120,03], EntityThaumcraftGolem['Golem'/79, l='MpServer', x=-841,47, y=63,00, z=192,88], EntityCorporeaSpark['Corporea Spark'/82, l='MpServer', x=-850,50, y=63,50, z=185,50], EntityCorporeaSpark['Corporea Spark'/83, l='MpServer', x=-851,50, y=63,50, z=184,50], EntityCorporeaSpark['Corporea Spark'/85, l='MpServer', x=-848,50, y=63,50, z=182,50], EntityItemFrame['entity.ItemFrame.name'/86, l='MpServer', x=-849,03, y=57,50, z=180,50], EntityThaumcraftGolem['Golem'/93, l='MpServer', x=-851,50, y=64,00, z=226,84], EntityThaumcraftGolem['Golem'/94, l='MpServer', x=-853,53, y=64,00, z=225,69]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 456866888 bytes (435 MB) / 969912320 bytes (924 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1763 8 mods loaded, 8 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1763.jar) 
    UCHIJAAAA   Forge{11.15.1.1763} [Minecraft Forge](forge-1.8.9-11.15.1.1763.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   Thaumcraft{5.1.6} [Thaumcraft](Thaumcraft-1.8.9-5.1.6.jar) 
    UCHIJAAAA   Botania{r1.8-249} [Botania](Botania.r1.8-248-MC1.8-0.6.1.jar) 
    UCHIJAAAA   mantle{1.8.9-0.8.2.jenkins95} [Mantle](Mantle-1.8.9-0.8.2.jar) 
    UCHIJAAAA   tconstruct{1.8.9-2.1.0.jenkins101} [Tinkers' Construct](TConstruct-1.8.9-2.1.0.jar) 
    Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)

```
GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'
Pulsar/tconstruct loaded Pulses: 
    - TinkerCommons (Enabled/Forced)
    - TinkerWorld (Enabled/Not Forced)
    - TinkerTools (Enabled/Not Forced)
    - TinkerSmeltery (Enabled/Not Forced)
    - TinkerGadgets (Enabled/Not Forced)
    - TinkerOredict (Enabled/Forced)
    - TinkerIntegration (Enabled/Forced)
    - TinkerFluids (Enabled/Forced)
    - TinkerMaterials (Enabled/Forced)
    - TinkerDebug (Enabled/Not Forced)

Launched Version: 1.8.9-forge1.8.9-11.15.1.1763
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.4229, Intel
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: alternate_textures_futureazoo.zip
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz
```

**Comment by GirafiStudios** [comment] 2016-02-29 15:29
Duplicate of #134 ?

**Comment by Hyxaru** [comment] 2016-02-29 17:53
Looks similair.

**Comment by GirafiStudios** [comment] 2016-02-29 17:55
Biomes O' Plenty wouldn't have anything to do with this btw. This is just a random crash you can be unlucky to get when you logon to a server.

**Comment by Hyxaru** [comment] 2016-02-29 19:15
Removing BoP config along the actual mod doesn't solve the issue unfortunatly.

**Comment by williewillus** [comment] 2016-02-29 20:20
~~I think it's thaumcraft+botania. Will test with your modset later tonight~~

See #148

**Closed as completed** 2016-03-01 01:00 UTC
