### ISSUE TITLE
bug with Dynamic Surroundings

### ISSUE THREAD

**Issue by 0Navis0** [williewillus/Botania#458] opened 2016-08-25 21:12 UTC
There is a bug with the last Botania version wich cause some ambiance sounds from Dynamic Surroundings like the birds to bug and repeat them indefinitely.

**Comment by KingDGrizzle** [comment] 2016-08-25 21:14
Amm, don't get me wrong, but like.. Os there a "proof", like a console message or something? What Botania stuff were you using?

**Comment by Hypsellis** [comment] 2016-08-25 21:22
You're a pretty sticky are you, did you decide to follow me everywhere I go ?
Yes I have a proof since I passed one hour to try all the mods of my modpack ones by ones for knowing the cause of the problem. And there is no any crashreports or logs since it's an excecution problem wich doesn't prevent Minecraft to work correctly.

**Comment by utoc** [comment] 2016-08-28 11:09
I'm seeing a similar issue with the elevator from rfTools and the generator from DeepResonance that started after Botania r316.  If I remove Botania or downgrade it to r316, the sound repeating indefinitely issue is abated entirely. 

The only other way after r316 to get the noises to stop is to remove the block that causes them.  We also do not have any Bergamutes on the server or the test clients.

Discussed here: https://github.com/McJty/DeepResonance/issues/113

**Comment by vdrake77** [comment] 2016-09-03 18:13
As a workaround that doesn't require you to reset anything, mute your block sounds for a second and turn them back on, the audio is fixed until the next time you use those items.

**Comment by williewillus** [comment] 2016-09-03 22:00
fixed in next release, thanks for your patience

**Closed as completed** 2016-09-03 22:00 UTC

**Comment by McJty** [comment] 2016-09-07 12:04
Are you sure it is fixed for real? I'm getting reports on it again in release 320 of botania:

https://github.com/McJty/RFTools/issues/703#issuecomment-245255789

**Comment by williewillus** [comment] 2016-09-07 12:37
It's not in a release build yet. I'll probably put out a final build of Botania U within the next couple days now that vaz is back
