### ISSUE TITLE
1.8 Skin Issues

### ISSUE THREAD

**Issue by Aelar-Nailo** [williewillus/Botania#109] opened 2016-02-09 02:23 UTC
As expected, and as i am reasonably sure you know, the closest layer on the render of the armors of this mod conflicts with the new layer for skin customization in 1.8, so you get effects like this 
![2016-02-08_18 13 05](https://cloud.githubusercontent.com/assets/16912381/12905987/d490b6ac-ce90-11e5-85d1-000c44f384c0.png) and this
![2016-02-08_18 18 49](https://cloud.githubusercontent.com/assets/16912381/12905992/dafceb32-ce90-11e5-953c-01bf76ba0ec8.png) which are somewhat foolish looking. just wanted to make sure you were aware, in case you were using a 1.7 or lower skin. Have a good day!

**Comment by GirafiStudios** [comment] 2016-02-09 02:26
Similiar to https://github.com/williewillus/Botania/issues/52

**Comment by williewillus** [comment] 2016-02-09 04:13
yeah dupe of #52, thanks for the report though!!

**Comment by williewillus** [comment] 2016-02-28 18:20
Actuallly a separate issue it appears

**Comment by yrsegal** [comment] 2016-02-28 18:20
yeah, this requires changing the model slightly

**Comment by yrsegal** [comment] 2016-06-06 01:34
Is this actually that big an issue? There are no Z-fights, and it can look super stylish.

**Comment by PsiGuy60** [comment] 2016-07-23 19:45
You're right that there's no Z-fighting. However, there's another problem in that the "backpiece" of the armor goes into the player's skin and goes invisible.

![minecraft_derpy_armor](https://cloud.githubusercontent.com/assets/13868023/17079901/49be42ea-511e-11e6-929c-dc5cd4fb9e29.jpg) Picture for reference, notice how the bottom part of the Manasteel chestplate is invisible on the player but renders on the armor stand.

There also appears to be some minor Z-fighting between the boots and leggings.

**Comment by Lashriel** [comment] 2016-07-23 20:05
Armor models in general need to be fixed. There's a persistent issue, that by the way also happens in the 1.7.10 version (ie Vazkii's version) so I'm not making an issue for it here, where armor just sort of goes into the player's back.
![minecraft_derpy_armor](https://cloud.githubusercontent.com/assets/13868023/17080004/82a21f52-5121-11e6-9a35-8c04651b50ad.jpg)

Picture for reference, note the part that does render on the armor stand but doesn't on the player.
There also appears to be some Z-fighting between the Mana/Terrasteel boots and leggings, as well as on all helmets. This isn't visible in the screenshots but it's much more obvious in-person.

Apologies for hijacking, just thought that if someone's going to work on armor models they should also know about those things and hopefully fix them.

On an entirely unrelated note, why do the armors move around on armor stands?

**Comment by williewillus** [comment] 2016-07-23 20:09
if someone fixes it i'll take I don't have the original model files :P

**Comment by yrsegal** [comment] 2016-07-23 20:38
@wiiv might

**Comment by williewillus** [comment] 2016-07-23 20:58
whoever has a problem with it talk to wiiv directly, as I don't really see waht's wrong with it right now

As for the breathing on the armor stand, no idea :/

**Comment by williewillus** [comment] 2016-09-05 22:56
https://github.com/Vazkii/BotaniaV2/issues/9

**Closed as completed by williewillus** 2016-09-05 22:56 UTC
Labels: rendering
