### ISSUE TITLE
Spreader crashes client when unloaded

### ISSUE THREAD

**Issue by TheWhiteWolves** [williewillus/Botania#46] opened 2016-01-17 01:19 UTC
Copied over from Botania Issues - [Issue #1756](https://github.com/Vazkii/Botania/issues/1756)

> Using r1.8-248 on a minecraft 1.8.9 server.  Placed the spreader (missing item texture btw) near some daybloom/nightshade primus flowers then teleported away.  No chunkloading.  Got this crash:
> 
> http://pastebin.com/ZGdSkeuz
> 
> Very repeatable.

**Comment by GirafiStudios** [comment] 2016-01-17 01:22
Ugh, pretty sure this got fixed a while ago.. Sure the guy is using the latest version. Most of the version is called r1.8-248 internally.

**Comment by williewillus** [comment] 2016-01-17 01:53
Yeah, they must've been using a jar they compiled on their own, all of my public builds have the commit ID appended, which makes it impossible to tell what version they're on :p

**Comment by williewillus** [comment] 2016-01-17 02:00
Yeah can't reproduce in latest dev, closing unless they show it happens in the latest build.

**Closed as completed by williewillus** 2016-01-17 02:00 UTC
