### ISSUE TITLE
(fps drop) Issues with floating flower

### ISSUE THREAD

**Issue by ghost** [williewillus/Botania#449] opened 2016-08-18 14:26 UTC
I've looked down the issues posted here, couldn't find it (At least, as close as this one)

I was playing with my friend on my modded server (Home made 1.10 /1.9.4), and we had botania installed. I made a lil' tree farm like one I've seen in a video, and we started having fps issus. we narrowed it down to the floating flowers by removing **ALL** the block around it, and as soon as we destroyed a floating munchdew, fps went from 15 to 32. I did the same with hopperhock, and the rannuncarpus : 
32 -> 40, then 40 -> 50 fps. For some reason, the agricarnation wasn't as bad, I had to break all 4 to get 
50 -> 60. Anyway, tought I'd let you know I had that bug in botania.

Botania version : r1.8-312
Forge version : 1.10-forge1.10-12.18.0.2000-1.10.0

Mod installed : BaseMetals, Baubles, BetterFps, Botania, ChestTransporter, ChunkAnimator, Damage indicator, DrCyanos-ore-spawn, easyBreading, IndustrialCraft2, JustEnoughItem, Mantle, OreDictionaryConverter, Power-Advantage, Reptile, StalkingCreeper, SteamAdvantage, Tinker'sConstruct.

I hope that any if this helps ! 
Have a good day.

**Comment by vladfrangu** [comment] 2016-08-18 14:27
Update to the latest Botania? I think this issue has aready been fixed

**Comment by williewillus** [comment] 2016-08-18 14:33
Not fully, I'm working on it

**Comment by williewillus** [comment] 2016-08-18 15:19
The model was ported straight from the old 1.7 techne model, and has a _ton_ of unneccessary faces. I need to remake the model so that it has fewer. And since I'm not that good at art/modeling it's slow going :P

**Comment by vladfrangu** [comment] 2016-08-18 17:06
I can probably help, if all you need is the base model

**Comment by williewillus** [comment] 2016-08-18 17:21
i remade the base model to have less quads. the grind I'm having right now is changing all the textures to account for it and to fix the UV's of the base model. It's on the improvedfloaters branch right now.

**Comment by vladfrangu** [comment] 2016-08-18 17:28
I'll look at it, and maybe do some changes, if you don't mind

**Comment by vladfrangu** [comment] 2016-08-18 17:28
In a separate file

**Comment by williewillus** [comment] 2016-08-18 17:36
sure

**Comment by vladfrangu** [comment] 2016-08-18 18:13
I will have to remake it as my program doesn't want to import the JSON, I'll PR when I finish it, or link you to it

**Comment by vladfrangu** [comment] 2016-08-18 18:20
UV will the the worst, as I don't know what to use for the side of the first layer.

**Comment by vladfrangu** [comment] 2016-08-18 18:39
I've made the "bare" model, need to test it, and to fix a issue, cause I'm using a texture that will have to be added.. As I added a green grass, thats not the grass path. If thats alright, I can probably PR in like 15 mins

**Comment by williewillus** [comment] 2016-08-20 01:22
dupe of #414 either way, see that for further discussion

**Closed as completed by williewillus** 2016-08-20 01:22 UTC
