### ISSUE TITLE
Breaking Mana Pool while Mana Tablet is on it, it crashes both Client and Server

### ISSUE THREAD

**Issue by Carrots4U** [williewillus/Botania#339] opened 2016-06-12 21:09 UTC
If you break a mana pool when there is still a mana tablet is on it both the client and the server crash. 

Server crashlog: http://pastebin.com/GnD5huN5
Client crashlog: http://pastebin.com/3PTDg2e1

**Comment by williewillus** [comment] 2016-06-12 21:32
I don't think the tablet has anything to do with it, the crashlog says it's a spreader, making this a duplicate of #329

**Closed as completed by williewillus** 2016-06-12 21:32 UTC
