### ISSUE TITLE
Crash when using Rod of the Terra Firma

### ISSUE THREAD

**Issue by TheWhiteWolves** [williewillus/Botania#100] opened 2016-02-06 20:23 UTC
[Crash Log from Taiga Biome](http://pastebin.com/zMXV3bhA)

[Crash Log from Desert Biome](http://pastebin.com/cDMtjvG4)

Looks to be something coming in null

---

Instance:
minecraft-1.8.9
forge-11.15.1.1732

Mods:
Baubles-1.8.9-1.1.3.0
Botania.r1.8-248-MC1.8-779cc76
jei_1.8.9-2.25.6.140
journeymap-1.8.8-5.1.3-unlimited
InventoryTweaks-1.60-beta-30

**Comment by williewillus** [comment] 2016-02-06 20:35
Duplicate of #90 ;  fixed in next build

**Closed as completed by williewillus** 2016-02-06 20:36 UTC
