### ISSUE TITLE
Double chest with double corporea spark

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#81] opened 2016-01-26 18:12 UTC
When an item is requested from an inventory with two sparks on top of it, like a double chest, more items then requested are drawn from it but the right amount of items are dropped: item loss.

As a sidenote/reminder, in 1.8 item frames can rotate their holding item eight times as oposed to four in previous versions. Additional request multipliers might me required. Right now the block freezes upon getting an invalid request. The game doesn't crash fortunatly.

**Comment by williewillus** [comment] 2016-01-26 18:40
instead of 
1 16 32 64 (then crashes for the rest), we now have

~~1 16 24 32 40 48 56 64~~
Will be 1 2 4 8 16 32 48 64 in next build

**Comment by Hyxaru** [comment] 2016-01-26 19:14
As a small reminder if not already done, the lexica entry might need an update then.

**Comment by yrsegal** [comment] 2016-01-26 19:15
It got one.

**Comment by williewillus** [comment] 2016-01-26 19:43
Actually, only half of this issue was fixed (item frames)

Can you reproduce the first issue (double sparks) in 1.7?

**Comment by williewillus** [comment] 2016-02-09 04:29
I can't reproduce the double spark issue.

Have a chest with master spark, then a double chest with two sparks with some cobble in both halves. Both an index and funnel return and deduct the correct amounts

**Comment by Lashriel** [comment] 2016-02-29 08:18
I think there was an issue about the double-chest/double-spark behaviour on Vazkii's GitHub that got closed because _you don't need double sparks in the first place_.

EDIT: Found it. https://github.com/Vazkii/Botania/issues/1545

**Comment by williewillus** [comment] 2016-03-01 02:24
Closing until further response by assuming OP ran into the above situation

**Closed as completed by williewillus** 2016-03-01 02:24 UTC
Labels: mechanic, cant-reproduce
