### ISSUE TITLE
Ticking player crash when revived with golden laurel crown

### ISSUE THREAD

**Issue by Phizzhead** [williewillus/Botania#378] opened 2016-06-27 02:31 UTC
https://gist.github.com/Phizzhead/831cdfe75cedecb20e3458add47c34e8

**Comment by williewillus** [comment] 2016-06-28 01:28
can't reproduce

**Comment by williewillus** [comment] 2016-06-28 01:28
what potion effects did you have as you died?

**Comment by vladfrangu** [comment] 2016-07-31 12:43
Did you have any armor that boosts health?

Did you have any potion effects?

You didn't really give @williewillus much info, soo, it can't really be considered a bug, I will try using Blood Magics armor that adds extra health

**Comment by vladfrangu** [comment] 2016-07-31 15:02
Can't reproduce with Blood Magic / Health boost atribute

**Comment by williewillus** [comment] 2016-09-05 22:22
No update, closing

**Closed as completed by williewillus** 2016-09-05 22:22 UTC
Labels: priority-medium
