### ISSUE TITLE
abstruse/spectral/infrangible platform crash

### ISSUE THREAD

**Issue by Thurii** [williewillus/Botania#341] opened 2016-06-13 18:38 UTC
**Botania Version:** Botania-unofficial.r1.8-308
**Forge Version:** forge-1.9.4-12.17.0.1939

The game crashes when you sprint on abstruse/spectral/infrangible platforms. The crash seems to happen when the game creates the sprinting particles. Falling/jumping on the platforms doesn't create particles or crash the game.

**FML Log:** http://pastebin.com/ma3NRgU7

**Comment by PlasmaPower** [comment] 2016-06-13 19:02
As the crash handler goes into ColorHandler into World, it would appear to be the getTileEntity call [here](https://github.com/williewillus/Botania/blob/MC19/src/main/java/vazkii/botania/client/core/handler/ColorHandler.java#L88). I'm a new to this codebase, but I would expect that the platforms are tile entities as expected, meaning that the position is incorrect. That position is coming straight from Minecraft though.

**Comment by yrsegal** [comment] 2016-06-13 19:18
Already fixed for the next version.

**Comment by PlasmaPower** [comment] 2016-06-13 19:23
Duplicate of #330 then? It looks like some null checks were previously missing (fixed in f56eca23fc6fac9056d0af86e8ee5171f2e05a6d).

**Comment by yrsegal** [comment] 2016-06-13 19:24
yep. This can be closed.

**Closed as completed** 2016-06-13 20:36 UTC
