### ISSUE TITLE
[1.9] BlockAltar.getLightValue crash

### ISSUE THREAD

**Issue by gazpachoking** [williewillus/Botania#249] opened 2016-04-19 01:46 UTC
I was putting a polished stone slab from Quark near a petal apothecary using a building blocks trowel when this crash happened. Not sure if it's botania's issue, due to the multiple mods involved, but figured I'd report.

Using pre-release build 301

https://gist.github.com/gazpachoking/5dc5ec9c3344112227a11a941b23a931

**Comment by yrsegal** [comment] 2016-04-19 01:47
Dupe of #221

**Comment by williewillus** [comment] 2016-04-19 01:48
Yes dupe, and it's a Forge bug, pending a response from them. I'll probably add some workaround checks in the meantime if they don't respond soon

**Closed as completed by williewillus** 2016-04-19 01:48 UTC

**Comment by gazpachoking** [comment] 2016-04-19 02:40
Oops, sorry about the dupe. Saw this in your forge issue, 

> Note that this ONLY happens when digging in survival

Just thought I'd mention that I was placing a block when it happened, and it now happens every time I load the world.
