### ISSUE TITLE
ghostRail cause server crashed

### ISSUE THREAD

**Issue by bunSakurAing** [williewillus/Botania#180] opened 2016-03-13 11:35 UTC
crash report:
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.1.jar)
  SpongeCoremod (spongeforge-1.8.9-1763-4.1.0-BETA-1203.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 16-3-13 下午7:21
Description: Exception while updating neighbours

java.lang.NullPointerException: Exception while updating neighbours
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
    at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:40)
    at com.google.common.collect.ImmutableList.of(ImmutableList.java:89)
    at net.minecraft.block.BlockRailBase.getManipulators(BlockRailBase.java:51)
    at net.minecraft.block.BlockRailBase.getManipulators(BlockRailBase.java:46)
    at net.minecraft.block.state.BlockState$StateImplementation.getManipulators(BlockState.java:128)
    at net.minecraft.block.state.BlockState$StateImplementation.populateKeyValues(BlockState.java:273)
    at net.minecraft.block.state.BlockState$StateImplementation.getValues(BlockState.java:318)
    at org.spongepowered.common.block.SpongeBlockSnapshot.<init>(SpongeBlockSnapshot.java:105)
    at org.spongepowered.common.block.SpongeBlockSnapshot.<init>(SpongeBlockSnapshot.java:93)
    at net.minecraft.world.World.createSpongeBlockSnapshot(World.java:273)
    at net.minecraft.world.World.createSpongeBlockSnapshot(World.java:164)
    at net.minecraft.world.World.func_180501_a(World.java:140)
    at net.minecraft.world.World.func_175698_g(World.java:367)
    at net.minecraft.block.BlockRailBase.func_176204_a(BlockRailBase.java:131)
    at org.spongepowered.common.event.CauseTracker.notifyBlockOfStateChange(CauseTracker.java:1124)
    at net.minecraft.world.World.func_175685_c(World.java:337)
    at net.minecraft.world.World.func_175722_b(World.java:409)
    at net.minecraft.world.World.markAndNotifyNeighbors(World.java:217)
    at org.spongepowered.common.event.CauseTracker.markAndNotifyBlockPost(CauseTracker.java:1194)
    at org.spongepowered.common.event.CauseTracker.handleBlockCaptures(CauseTracker.java:833)
    at org.spongepowered.common.event.CauseTracker.handlePostTickCaptures(CauseTracker.java:445)
    at org.spongepowered.common.event.CauseTracker.randomTickBlock(CauseTracker.java:1068)
    at net.minecraft.world.WorldServer.redirect$onUpdateBlocks$0(WorldServer.java:120)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:431)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
    at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:40)
    at com.google.common.collect.ImmutableList.of(ImmutableList.java:89)
    at net.minecraft.block.BlockRailBase.getManipulators(BlockRailBase.java:51)
    at net.minecraft.block.BlockRailBase.getManipulators(BlockRailBase.java:46)
    at net.minecraft.block.state.BlockState$StateImplementation.getManipulators(BlockState.java:128)
    at net.minecraft.block.state.BlockState$StateImplementation.populateKeyValues(BlockState.java:273)
    at net.minecraft.block.state.BlockState$StateImplementation.getValues(BlockState.java:318)
    at org.spongepowered.common.block.SpongeBlockSnapshot.<init>(SpongeBlockSnapshot.java:105)
    at org.spongepowered.common.block.SpongeBlockSnapshot.<init>(SpongeBlockSnapshot.java:93)
    at net.minecraft.world.World.createSpongeBlockSnapshot(World.java:273)
    at net.minecraft.world.World.createSpongeBlockSnapshot(World.java:164)
    at net.minecraft.world.World.func_180501_a(World.java:140)
    at net.minecraft.world.World.func_175698_g(World.java:367)
    at net.minecraft.block.BlockRailBase.func_176204_a(BlockRailBase.java:131)

-- Block being updated --
Details:
    Block: botania:ghostRail[shape=north_south]
    Block location: World: (142,69,2079), Chunk: (at 14,4,15 in 8,129; contains blocks 128,0,2064 to 143,255,2079), Region: (0,4; contains chunks 0,128 to 31,159, blocks 0,0,2048 to 511,255,2559)
Stacktrace:
    at org.spongepowered.common.event.CauseTracker.notifyBlockOfStateChange(CauseTracker.java:1124)
    at net.minecraft.world.World.func_175685_c(World.java:337)
    at net.minecraft.world.World.func_175722_b(World.java:409)
    at net.minecraft.world.World.markAndNotifyNeighbors(World.java:217)
    at org.spongepowered.common.event.CauseTracker.markAndNotifyBlockPost(CauseTracker.java:1194)
    at org.spongepowered.common.event.CauseTracker.handleBlockCaptures(CauseTracker.java:833)
    at org.spongepowered.common.event.CauseTracker.handlePostTickCaptures(CauseTracker.java:445)
    at org.spongepowered.common.event.CauseTracker.randomTickBlock(CauseTracker.java:1068)
    at net.minecraft.world.WorldServer.redirect$onUpdateBlocks$0(WorldServer.java:120)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:431)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)

-- Affected level --
Details:
    Level name: sc
    All players: 6 total; [EntityPlayerMP['birddy'/301871, l='sc', x=-305.54, y=72.23, z=-158.97], EntityPlayerMP['Flyingsongs'/686405, l='sc', x=-176.30, y=61.00, z=-559.68], EntityPlayerMP['OnikawaTatsuya'/975013, l='sc', x=141.57, y=70.00, z=2079.17], EntityPlayerMP['Slayers_Zhao'/993693, l='sc', x=155.30, y=72.00, z=2059.59], EntityPlayerMP['Uni_G'/1003609, l='sc', x=65.85, y=83.25, z=-394.02], EntityPlayerMP['lzb'/1110736, l='sc', x=630.96, y=41.00, z=-356.22]]
    Chunk stats: ServerChunkCache: 1625 Drop: 0
    Level seed: 8701121421996264922
    Level generator: ID 10 - BIOMESOP, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: -315.00,72.00,-123.00 - World: (-315,72,-123), Chunk: (at 5,4,5 in -20,-8; contains blocks -320,0,-128 to -305,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 23959960 game time, 16331087 day time
    Level dimension: 5
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Linux (amd64) version 2.6.32-573.7.1.el6.x86_64
    Java Version: 1.8.0_65, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 879632536 bytes (838 MB) / 2520498176 bytes (2403 MB) up to 8432910336 bytes (8042 MB)
    JVM Flags: 4 total; -Xms256M -XX:+UseConcMarkSweepGC -Xmx8192M -XX:MaxPermSize=128M
    IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
    FML: MCP 9.19 Powered by Forge 11.15.1.1764 28 mods loaded, 28 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](paperspigot-1.8.8.jar) 
    UCHIJAAAA   Forge{11.15.1.1764} [Minecraft Forge](paperspigot-1.8.8.jar) 
    UCHIJAAAA   sponge{1.8.9-1763-4.1.0-BETA-1203} [SpongeForge](spongeforge-1.8.9-1763-4.1.0-BETA-1203.jar) 
    UCHIJAAAA   io.github.hsyyid.adminshop{1.5} [AdminShop](AdminShop-1.5.jar) 
    UCHIJAAAA   ArchitectureCraft{1.4.0} [ArchitectureCraft](ArchitectureCraft-1.4.0-mc1.8.9.jar) 
    UCHIJAAAA   BiomesOPlenty{3.0.0} [Biomes O' Plenty](BiomesOPlenty-1.8.9-3.0.0.1927-universal.jar) 
    UCHIJAAAA   com.gmail.trentech.bloodmoney{0.2.9} [Blood Money](bloodmoney-4.1.0-0.2.9.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   Thaumcraft{5.2.1} [Thaumcraft](Thaumcraft-1.8.9-5.2.1.jar) 
    UCHIJAAAA   Botania{r1.8-250} [Botania](Botania.r1.8-unofficial-0.6.4.2.jar) 
    UCHIJAAAA   chiselsandbits{mc1.8.9-v1.8.11} [Chisels & Bits](chiselsandbits-mc1.8.9-v1.8.11.jar) 
    UCHIJAAAA   io.github.hsyyid.commandsigns{1.0} [CommandSigns](CommandSigns-1.0.jar) 
    UCHIJAAAA   customnpcs{1.8.9_beta} [CustomNPCs](CustomNpcs_1.8.9_beta%2821feb16%29.jar) 
    UCHIJAAAA   EconomyLite{1.2.0} [EconomyLite](EconomyLite-v1.2.0.jar) 
    UCHIJAAAA   io.github.hsyyid.essentialcmds{7.8c-23b5a56} [EssentialCmds](EssentialCmds-7.8c.jar) 
    UCHIJAAAA   flexiblelogin{0.6.1} [FlexibleLogin](FlexibleLogin.jar) 
    UCHIJAAAA   foodcraft{1.2.0} [FoodCraft](FoodCraft-16.2.4-1.2.2-1.8.9.jar) 
    UCHIJAAAA   journeymap{1.8.9-5.1.5} [JourneyMap](journeymap-1.8.9-5.1.5-unlimited.jar) 
    UCHIJAAAA   Keys{1.0} [Keys](Keys-1.0.1.jar) 
    UCHIJAAAA   looty{0.9.0} [RPG Looty](looty-0-9.jar) 
    UCHIJAAAA   mantle{1.8.9-0.8.2.jenkins95} [Mantle](Mantle-1.8.9-0.8.2.jar) 
    UCHIJAAAA   MoreFurnaces{1.5.0} [More Furnaces](morefurnaces-1.5.0-MC1.8.9.jar) 
    UCHIJAAAA   Morpheus{1.8.8-2.0.55} [Morpheus](Morpheus-1.8.8-2.0.55.jar) 
    UCHIJAAAA   ninja.leaping.permissionsex{2.0-SNAPSHOT} [PermissionsEx](PermissionsEx-Sponge.jar) 
    UCHIJAAAA   PJW{0.7.53} [Project Worlds](projectworlds-3.1.0-v0.7.53.jar) 
    UCHIJAAAA   tconstruct{1.8.9-2.1.0.jenkins101} [Tinkers' Construct](TConstruct-1.8.9-2.1.0.jar) 
    UCHIJAAAA   worldedit{6.1.1} [WorldEdit](worldedit-forge-mc1.8.9-6.1.1.jar) 
    Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.1.jar)

SpongeCoremod (spongeforge-1.8.9-1763-4.1.0-BETA-1203.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - TinkerDebug (Enabled/Not Forced)

```
Profiler Position: N/A (disabled)
Player Count: 7 / 50; [EntityPlayerMP['birddy'/301871, l='sc', x=-305.54, y=72.23, z=-158.97], EntityPlayerMP['Flyingsongs'/686405, l='sc', x=-176.30, y=61.00, z=-559.68], EntityPlayerMP['LuCiel'/969552, l='world', x=-2813.94, y=66.00, z=-400.39], EntityPlayerMP['OnikawaTatsuya'/975013, l='sc', x=141.57, y=70.00, z=2079.17], EntityPlayerMP['Slayers_Zhao'/993693, l='sc', x=155.30, y=72.00, z=2059.59], EntityPlayerMP['Uni_G'/1003609, l='sc', x=65.85, y=83.25, z=-394.02], EntityPlayerMP['lzb'/1110736, l='sc', x=630.96, y=41.00, z=-356.22]]
Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
Type: Dedicated Server (map_server.txt)`
```

Placing the ghostRail will cause the server to crash, and will not destroy the ghostRail.

**Comment by williewillus** [comment] 2016-03-13 17:31
Cannot reproduce

Try on latest botania and without Sponge

**Comment by williewillus** [comment] 2016-03-13 20:59
Fixed in next sponge

**Closed as completed by williewillus** 2016-03-13 20:59 UTC
Labels: cant-reproduce
